### ISSUE TITLE
Support SPAs

### ISSUE THREAD

**Issue by jon49** [apiel/adka_server#1]
If there is no html file what does it use? Does it a 404.html file somewhere?

**Comment by apiel** [comment]
I am not sure to understand your question... Do you ask how to define custom 404 message responses?

This server is intended to serve static files during development process. Or in production I would recommend to use something like nginx. Right now in case of 404, you would only get a predefined error not customisable. I have to see if I can provide a way to make it customisable, that would not conflict with static html files.

Also, I am not so sure how your title is related to your question. How does SPA is related to 404? In a single page application, you would serve everything inside index.html and then your router would take care to handle not existing pages... so this is why I am not sure to understand your issue

**Comment by jon49** [comment]
For SPA back ends you typically redirect any pages to the single `index.html` file. So, I guess I'm asking for a way to using your static file server to allow for a 404 page to be served instead, or even give a way to redirect to that index.html file. Nodejs static file servers typically do something similar.

You can see in this static file server how it does it. https://www.npmjs.com/package/http-server#magic-files

**Comment by apiel** [comment]
Done in https://github.com/apiel/adka_server/commit/d69cfbd7f852c676378f35591375a1f7ef88da5a
